# -*- coding: utf-8 -*-
"""
Created on Mon May  7 15:18:13 2018

@author: Adarsh
"""





dict1={}
dict1['functionality']=['functionality','purpose','use','process','service','component','ambition','aspiration', 'desire', 'determination',
'direction',
'function',
'goal',
'idea',
'intent',
'objective',
'plan',
'principle',
'project',
'reason',
'scheme',
'scope',
'target',
'view',
'wish',
'animus',
'bourn',
'calculation',
'design',
'destination',
'dream',
'drift',
'end',
'expectation',
'hope',
'mecca',
'mission',
'object',
'point',
'premeditation',
'proposal',
'proposition',
'prospect',
'resolve',
'will',
'big idea',
'intendment',
'ulterior motive',
'whatfor',
'whyfor','adoption',
'benefit',
'handling',
'help',
'need',
'operation',
'practice',
'purpose',
'service',
'treatment',
'usage',
'value',
'account',
'advantage',
'appliance',
'applicability',
'appropriateness',
'avail',
'call',
'capitalization',
'cause',
'convenience',
'custom',
'end',
'exercise',
'exercising',
'exertion',
'fitness',
'good',
'habit',
'helpfulness',
'mileage',
'mobilization',
'necessity',
'object',
'occasion',
'point',
'profit',
'reason',
'relevance',
'serviceability',
'usability',
'usefulness',
'utility',
'way',
'worth']
dict1['weight']=['heavy''light','burden',
'density',
'gravity',
'heft',
'load',
'pressure',
'substance',
'adiposity',
'avoirdupois',
'ballast',
'gross',
'heftiness',
'mass',
'measurement',
'net',
'ponderosity','amount',
'bundle',
'capacity',
'consignment',
'goods',
'haul',
'payload',
'shipment',
'weight',
'bale',
'charge',
'contents',
'encumbrance',
'heft',
'hindrance',
'lading',
'mass',
'pack',
'parcel',
'part',
'shot']
dict1['price']=['price','benefit', 'pardon', 'forgiveness', 'gain', 'advantage', 'reward', 'award','cause', 'penalty', 'punishment','amount',
'bill',
'cost',
'demand',
'discount',
'estimate',
'expenditure',
'expense',
'fare',
'fee',
'figure',
'output',
'pay',
'payment',
'premium',
'rate',
'return',
'tariff',
'valuation',
'worth',
'appraisal',
'assessment',
'barter',
'bounty',
'ceiling',
'charge',
'compensation',
'consideration',
'damage',
'disbursement',
'dues',
'exaction',
'hire',
'outlay',
'prize',
'quotation',
'ransom',
'reckoning',
'retail',
'reward',
'score',
'sticker',
'tab',
'ticket',
'toll',
'tune',
'wages',
'wholesale',
'appraisement']
dict1['appearance']=['arrival','appearance',
'debut',
'display',
'presence',
'presentation',
'actualization',
'advent',
'appearing',
'coming',
'emergence',
'entrance',
'exhibition',
'introduction',
'manifestation',
'materialization',
'representation',
'unveiling',
'act',
'array',
'demonstration',
'example',
'exhibit',
'parade',
'presentation',
'affectation',
'arrangement',
'blaze',
'bravura',
'dash',
'exhibition',
'expo',
'exposition',
'exposure',
'fanfare',
'flourish',
'frame-up',
'frippery',
'front',
'layout',
'manifestation',
'ostentation',
'ostentatiousness',
'pageant',
'panorama',
'pedantry',
'pomp',
'pretension',
'pretentiousness',
'revelation',
'sample',
'scheme',
'shine',
'showboat',
'splash',
'splendor',
'splurge',
'spread',
'unfolding',
'vanity','sleekness',
' absence', 'end', 'departure', 'conclusion', 'exit', 'reality', 'disappearance',' loss', 'exodus', 'departure', 'removal', 'melting', 'retirement', 'flight', 'evanescence', 'wane', 'dissolution', 'escape', 'eclipse', 'dispersal', 'evaporation', 'recession', 'desertion', 'going', 'exit', 'withdrawal', 'dissipation','passing', 'disintegration', 'fading', 'ebbing', 'receding']



dict1['behavior']=['behavior','style','management', 'nature', 'practice', 'presence', 'demeanor', 'attitude', 'role', 'act', 'action', 'conduct', 'bearing', 'code', 'observance', 'morals', 'etiquette', 'taste', 'course', 'tone', 'deed', 'mien', 'decorum', 'carriage', 'comportment', 'speech', 'way', 'routine', 'seemliness', 'savoir-faire', 'form', 'convention', 'tact', 'delivery', 'dealings', 'decency', 'address', 'front', 'ethics', 'bag', 'ritual','propriety', 'deportment', 'mode', 'guise', 'expression', 'talk', 'social graces', 'ways', 'habits', 'tenue', 'way of life',"what's done",'listening', 'immorality', 'rest', 'impropriety', 'silence', 'quiet','bad manners', 'indecency', 'thoughtlessness', 'carelessness', 'stoppage', 'repose', 'inertia', 'inactivity', 'idleness', 'cessation']

dict1['performance']=['performance','work', 'act', 'achievement', 'conduct', 'completion', 'enforcement', 'fruition', 'consummation', 'administration', 'attainment', 'exploit', 'fulfillment', 'realization', 'discharge', 'execution', 'feat', 'doing', 'pursuance', 'carrying out','direction', 'unfulfillment', 'neglect', 'failure', 'inefficiency', 'ineffectualness', 'disregard']
dict1['quality']=['aspect','quality','inferior','better', 'best', 'necessary', 'major', 'important', 'superior', 'foremost', 'first-rate', 'first-class', 'extraordinary', 'chief',
'character',
'condition',
'element',
'kind',
'nature',
'trait',
'affection',
'affirmation',
'attribute',
'constitution',
'description',
'endowment',
'essence',
'factor',
'genius',
'individuality',
'make',
'mark',
'parameter',
'peculiarity',
'predication',
'property',
'savor',
'sort',
'virtue',
'name of tune',
'nature of beast',
'way of it','noun circumstances',
'action',
'case',
'plight',
'position',
'quality',
'situation',
'status',
'ballgame',
'estate',
'happening',
'mode',
'order',
'posture',
'predicament',
'rank',
'repair',
'reputation',
'riff',
'scene',
'shape',
'sphere',
'spot',
'standing',
'state',
'trim',
'how it goes',
'how things are',
'how things stack up',
'lay of the land',
'like it is',
'size of it',
'state of affairs',
'status quo',
'way things are',
'way things shape up',
"where it's at",'reality']

dict1['service']=['service','aid', 'help','usage','injustice', 'disfavor', 'harm', 'hurt', 'insult', 'wrong', 'prejudice', 'outrage', 'detriment','injury', 'bad turn','utility', 'use', 'office', 'business', 'supply', 'assistance', 'work', 'account', 'benefit', 'maintenance', 'employment', 'utility', 'appropriateness', 'overhaul', 'advantage', 'dispensation', 'employ', 'value', 'labor', 'avail', 'favor', 'courtesy', 'applicability', 'fitness', 'relevance', 'indulgence', 'kindness', 'check', 'use', 'ministration', 'service','disservice', 'damage', 'disfavor', 'disadvantage', 'inappropriateness', 'loss', 'hurt', 'hindrance',
'account',
'assistance',
'benefit',
'business',
'duty',
'employment',
'maintenance',
'office',
'supply',
'use',
'utility',
'work',
'advantage',
'applicability',
'appropriateness',
'avail',
'check',
'courtesy',
'dispensation',
'employ',
'favor',
'fitness',
'indulgence',
'kindness',
'labor',
'ministration',
'overhaul',
'relevance',
'serviceability',
'servicing',
'usefulness',
'value']

dict1['size']=['extent', 'bulk of some dimension',
'amount',
'breadth',
'capacity',
'content',
'diameter',
'extent',
'height',
'intensity',
'length',
'magnitude',
'proportion',
'range',
'scope',
'stature',
'volume',
'width',
'amplitude',
'area',
'bigness',
'body',
'caliber',
'capaciousness',
'dimensions',
'enormity',
'extension',
'greatness',
'highness',
'immensity',
'largeness',
'mass',
'measurement',
'proportions',
'spread',
'stretch',
'substance',
'substantiality',
'tonnage',
'vastness',
'voluminosity',
'admeasurement',
'hugeness','tininess', 'unimportance', 'smallness', 'insignificance','big']